### ISSUE TITLE
Setup proper development branching

### ISSUE THREAD

**Issue by RinMinase** [RinMinase/anidb#27]
**Todo:**
- [ ] Setup dev branch for non-deployment of Travis
- [ ] On push of master branch
  - Run test scripts
  - Build master branch -- deploying to firebase

**Comment by RinMinase** [comment]
**Todo:**
- [ ] Setup dev branch for non-deployment of Travis
- [ ] On push of master branch
  - Run test scripts
  - Build master branch -- deploying to firebase
