### ISSUE TITLE
Prefilter search in home before displaying

### ISSUE THREAD

**Issue by RinMinase** [RinMinase/anidb#46]
**Note:**
_This is to not use the " | filter " directive_

**Todo:**
- [x] Migrate from " | filter " directive
- [x] Pre-filter from controller
- [x] Remove ng-filter package (if possible or if unused)

**References:**
- [Tuning AngularJS, 4th Item](https://www.qualtrics.com/eng/tuning-angularjs-performance/)
